spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bankingmanagement
server:
  port: 1010

# to set log levels
logging:
  level:
    com:
      bankingmanagement: debug
  file:
    name: bankingmanagement.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

#actuator
management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,loggers,beans,mappings,threaddump,env,caches
  endpoint:
    health:
      show-details: always